In [1]:
ls

23nov_dummy_atom_scheme_v2_results.txt               24Nov_dummy_atom_scheme_conect_distances.txt         files/
23nov_dummy_atom_scheme_v2_results_0.25_cutoff.txt   Untitled.ipynb                                       init.ipynb
23nov_dummy_atom_scheme_v2_results_0.275_cutoff.txt  conect_distances.ipynb                               ligand_scanner_towards_dummy_scheme.txt
23nov_dummy_atom_scheme_v2_results_0.295_cutoff.txt  debugging_results.txt                                other_cutoffs.ipynb
23nov_dummy_atom_scheme_v2_results_0.310_cutoff.txt  debugging_results_5coord.txt                         v2.ipynb
23nov_dummy_atom_scheme_v2_results_w_files.txt       dummy_atom_scheme_v2.py


In [5]:
from numpy import *

In [6]:
results = eval(open('24Nov_dummy_atom_scheme_conect_distances.txt').read())

In [7]:
results

{'error_file_count': 0,
 'ligand_distances': [array([ 0.16884227,  0.21247764,  0.17619102,  0.1801343 ], dtype=float32),
  array([ 0.20049503,  0.17600982,  0.23691052], dtype=float32),
  array([ 0.16184485,  0.18292926,  0.18305866,  0.18447573], dtype=float32),
  array([ 0.19846642,  0.21329159,  0.19445275], dtype=float32),
  array([ 0.19183153,  0.22895852,  0.18808091], dtype=float32),
  array([ 0.23600093], dtype=float32),
  array([ 0.2251177 ,  0.23238814], dtype=float32),
  array([ 0.23188874,  0.21209922], dtype=float32),
  array([ 0.16062495,  0.25387287,  0.26612109,  0.26140529], dtype=float32),
  array([ 0.16043651,  0.25041431,  0.26202345,  0.2600697 ], dtype=float32),
  array([ 0.16058069,  0.23859799,  0.26511469,  0.26189563], dtype=float32),
  array([ 0.16055943,  0.25304797,  0.26601341,  0.26118502], dtype=float32),
  array([ 0.16049537,  0.25072923,  0.2643927 ,  0.26097426], dtype=float32),
  array([ 0.16060227,  0.2513659 ,  0.26308793,  0.26114494], dtype=floa

In [8]:
ligand_distances = results['ligand_distances']

In [12]:
all_distances = []

for i in ligand_distances:
    for j in i:
        all_distances.append(j)

In [13]:
all_distances

[0.16884227,
 0.21247764,
 0.17619102,
 0.1801343,
 0.20049503,
 0.17600982,
 0.23691052,
 0.16184485,
 0.18292926,
 0.18305866,
 0.18447573,
 0.19846642,
 0.21329159,
 0.19445275,
 0.19183153,
 0.22895852,
 0.18808091,
 0.23600093,
 0.2251177,
 0.23238814,
 0.23188874,
 0.21209922,
 0.16062495,
 0.25387287,
 0.26612109,
 0.26140529,
 0.16043651,
 0.25041431,
 0.26202345,
 0.2600697,
 0.16058069,
 0.23859799,
 0.26511469,
 0.26189563,
 0.16055943,
 0.25304797,
 0.26601341,
 0.26118502,
 0.16049537,
 0.25072923,
 0.2643927,
 0.26097426,
 0.16060227,
 0.2513659,
 0.26308793,
 0.26114494,
 0.16046138,
 0.24935414,
 0.26553294,
 0.26110294,
 0.16052368,
 0.23824486,
 0.26470488,
 0.26155326,
 0.16061257,
 0.25121251,
 0.26525769,
 0.261132,
 0.1605476,
 0.25198901,
 0.26233807,
 0.26133028,
 0.1604839,
 0.24774614,
 0.26312929,
 0.26165438,
 0.16055061,
 0.25316685,
 0.26424602,
 0.26068881,
 0.16049987,
 0.25079098,
 0.26446351,
 0.26106551,
 0.16075104,
 0.25820577,
 0.26071706,
 0.25964

In [14]:
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

In [36]:
plt.figure()
plt.hist(all_distances, bins = 5, range = (0, 0.5))

(array([  7.00000000e+00,   1.77490000e+04,   1.69090000e+05,
          7.46000000e+02,   1.66000000e+02]),
 array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5]),
 <a list of 5 Patch objects>)

In [37]:
plt.savefig('conect_dist_hist3.png')

In [19]:
len(all_distances)

188133

In [23]:
less_than_03 = 0

for i in all_distances:
    if i < 0.5:
        less_than_03 += 1
        
less_than_03        

187758